[package]
name = "sw8s_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sw8s_rust_lib"
path = "src/lib.rs"

[[bin]]
name = "sw8s_rust"
path = "src/main.rs"

[features]
jetson = []
logging = []

[dependencies]
opencv = "0.85.3" # Vision processing
tokio-serial = "5.4.1" # Async serial comms
tokio = { version = "1.29.1", features = ["full"] } # Async runtime
anyhow = "1.0.72" # Error handling
itertools = "0.11.0" # Enhance iterators
num-traits = "0.2.16" # Numeric generics
derive-getters = "0.3.0" # Getter macro
async-trait = "0.1.73" # Async fns in trait definitions
futures = { version = "0.3.28", default-features = false, features = ["std"] }# Futures utilities
toml = "0.8.1" # Configuration file
serde = { version = "1.0.188", features = ["derive"] } # Config serial handling
bytes = "1.5.0" # Byte buffering

[dev-dependencies]
assert_approx_eq = "1.1.0" # Floating point eq
reqwest = "0.11.20" # Downloading godot sim

[target.'cfg(target_os = "linux")'.dev-dependencies]
flate2 = "1.0.27" # Decompressing gz
tar = "0.4.40" # Unpacking tar

[target.'cfg(not(target_os = "linux"))'.dev-dependencies]
zip-extract = "0.1.2" # Decompressing zip
